[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = "0.8.28"
via_ir = false
optimizer = true
optimizer_runs = 10_000
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.5.0/",
    "@openzeppelin-contracts-5.5.0/=dependencies/@openzeppelin-contracts-5.5.0/",
    "@openzeppelin-contracts-upgradeable-5.5.0/=dependencies/@openzeppelin-contracts-upgradeable-5.5.0/",
    "@sushiswap-v3-core/=dependencies/@sushiswap-v3-core-v1/contracts/",
    "forge-std/=dependencies/forge-std-1.14.0/src/",
]

[dependencies]
forge-std = { version = "1.14.0" }
"@openzeppelin-contracts-upgradeable" = { version = "5.5.0" }
"@openzeppelin-contracts" = { version = "5.5.0" }
"@sushiswap-v3-core" = { version = "v1", git = "https://github.com/sushiswap/v3-core", rev = "21dfbed6b5e343559a14a7825e3d2f3be2611d8a" }

[fmt]
sort_imports = true
bracket_spacing = true
wrap_comments = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"

[fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
