// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

interface IAddressGaugeVoter {
    /// @notice autogenerated epoch id based on elapsed time
    function epochId() external view returns (uint256);
}
